### ISSUE TITLE
Ctrl + T opens up a new Tab

### ISSUE THREAD

**Issue by rclai** [JackAdams/temple#2]
I had to do `Session.set('Temple_activated', true)` to get it to work lol.

Using CHrome.

**Comment by JackAdams** [comment]
Weird. I tried it in chrome (Version 41.0.2272.89) just now and it worked.  Have made a little change which might help.

**Comment by JackAdams** [comment]
Are you sure it was Ctrl + T, not command + T?  On Chrome 41 (mac) it's command + T that opens tabs.

**Comment by rootedsoftware** [comment]
+1 same problem. Control + t doesn't do anything neither does Control + Shift + t. 

Version 46.0.2490.80 (64-bit) on Mac

**Comment by JackAdams** [comment]
This package is best used in conjunction with [constellation:console](constellation-demo.meteor.com).  It gives it a better UI and you don't have to worry about hotkey activation anymore.
